checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    external_code_coverage: true
    pylint:
        python_version: {{cookiecutter.python_major_version}}
        config_file: '.pylintrc'
